server: 
  port: 9527
 
spring: 
  application:
    name: springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 

zuul:
  #路由前缀
  prefix: /cps
  #忽视原真实服务名
  ignored-services: "*" #单个忽视springcloud-web-provider
  #路由配置
  routes:
    mydept.serviceId: springcloud-web-provider
    mydept.path: /mydept/**

info:
  app.name: springcloud
  company.name: www.nianshaoyouwei.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$

